-- How many distinct terms are in the sequence generated by a^b for
-- 2 <= a <= 100 and 2 <= b <= 100?

import Data.Set

solve :: Int
solve = size . fromList $ [a ^ b | a <- [2..100], b <- [2..100]]

main :: IO ()
main = print solve
